### ISSUE TITLE
登录输入密码后点击无反应，后台也没有记录

### ISSUE THREAD

**Issue by lyy0709** [what-the-fuck-ai/nexus#1]
![图片](https://github.com/what-the-fuck-ai/nexus/assets/65712338/4906d1fd-af03-487e-9ce5-2743c052e846)
v佬可以看看是不是有问题还是我的问题，session登录没有问题

**Comment by gngpp** [comment]
重点在这两个
<img width="599" alt="image" src="https://github.com/what-the-fuck-ai/nexus/assets/51810656/0b84ff5c-e7c1-47c9-97e1-ab887fe5c4c7">
endpoint是你出口域名/IP:端口，走tls的要设置--reverse
